name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
    deploy:
      strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest] # it creates 3X2=6 jobs as combination of os and images. if one job fails, all remaining ones cancel.
          images: [hello-world, alpine]                     # by using matrix, prevent the redundancy of enumarating one by one
          exclude:
            - images: alpine
              os: windows-latest
          include:
            - images: amd64/alpine
              os: ubuntu-20.04
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}