name: Exploring Variables and Secrets

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '*/1 * * * *'
  push:

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build # all docker command are dummy and for demo purposes
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: Docker Login
      run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish
      run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/main'  # reading a value from context and build a condition on it 
    needs: docker
    concurrency: 
      group: production-deployment # in most cases, concurrency in a job is not wanted for consistency 
      cancel-in-progress: false # toggling this decides first or second one will be terminated if concurrent requests happen
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      timeout-minutes: 1
      run: |
        echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        sleep 6000s